### PR TITLE
Projects

### LINKED ISSUE #14: LocalStorage for persistance
We can use `localforage` which is a nice and neat common interface to use localStorage and webSQL depending on the user-agent at the simultaneously.

This is needed, so that the user can continue editing from where the page was left

### LINKED ISSUE #15: Add a Project semantic and model
I think we need to define a model and semantics to what a `Project` is. 

This should be linked to #14 as the user may be working on different Flurstücken. In Addition, the user might want to download / share data, but not all at once.

For now, a `Project` should only hold a name. The user can then switch projects to load other features from the data-store.
A project could also be the place, where a user-account might be linked. I.e. guest users can only save to localstorage / files, while logged in users have X firebase projects.

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #15 closes #14

### CODE REVIEW

**Comment by mmaelicke** [comment]
@JesJehle this is now a working example for a vastly simplified project management. 

A project project is simply a string that identifies a set of features in the local storage. As soon as the features are changed, they will be saved 1 second later. If a project is switched, the data is changed as well. signals made this extremely easy....

@JesJehle  There is one thing we need to decide: currently the default project is `anonymous`, displayed as `kein Projekt`, which is always there and **does persist too**. I think it would be better, if the default, anonymous project does not store anything. This way, the application always starts clean. What do you think?

**Comment by JesJehle** [comment]
Hi Mirko,
here is a draft for a simple projekt management in whimsical:
image

https://whimsical.com/integra-YWXzyTALywxcgLRzS2Q3u3@VsSo8s35Wx4wfkSK25ws1J

**Comment by mmaelicke** [comment]
@JesJehle, this one is ready for review. 

Please note that there are two variants: this PR and #27 

#27 **hard-codes** the save indicator to be always visible with projects. This PR always the reflects the actual saving state. This is kind of better, but maybe distracting...

Please evaluate both PRs and accept one **and reject the other**

**Comment by JesJehle** [comment]
I think it's better to always show the actual state of the application to the user, but we need to do that in an not distracting way.
But is fine for now. 
I create issues for thinkgs to add

**Pull request merged**
