### PR TITLE
Draggable

### PR DESCRIPTION
**Pull request by mmaelicke**
Most basic first push of draggable trees and droppable map components.

Most of the heavy lifting of replacing the data model is implemented. Some things  are not yet calculated correctly. 
I will keep on pushing some improvements on this branch, and then request a PR.

### CODE REVIEW

**Comment by mmaelicke** [comment]
OK, the basic functionality is now kind of implemented again. 
Next, I think also on this branch, we should sort out how, if and when the tree ages can be set if a simulation is already in action. Currently I implemented two sliders, which is a bad option, but was straightforward and gave us all functionality (ie. after 20 years, plant trees, that can be 20yrs or 0yrs or anything in between...)

changing positions by drag and drop is not implemented, as I want to fix the base functionality first. The functionality needed to be implemented into the MainMap, which is not ideal, and dragging existing markers will make things worse. Thus, we implement that and after that, never touch this functionality again ^^

**Comment by mmaelicke** [comment]
I guess this one is ready for review. The StarRating component is currently showing hard coded numbers, until we updated the backend and have real data available. 

closes #94

**Comment by JesJehle** [comment]
Some UX improvements which can be implemented after merge.
Map:
- [ ] increase the size of the point of the selected tree. Make all other points more gray, to have a stronger visual distinction.
- [ ] Have a "start" simulation step, where all trees are visible, independent of age. Otherwise trees which dont start at the beginning are hidden. 
tree line editor:
see #92 
tree popover or SideTreeDetails:
see #94

**Review by JesJehle — APPROVED** [review]
This is great. Since there are quite many changes, I would merge them, and develop from there.
we can work on #94 #92 after.

**Pull request merged**
