### PR TITLE
Add blossoms tab

### LINKED ISSUE #132: Implement 'blüte' result card
**Blüte**: 
image
* **tab bar container** - horizontal barchart Blühzeitpunkt 
* **tab bar container** - stacked area chart Blühangebot (Nektar or Blüten or pollen (gespräch mit felix))
* **map** - tree icons (having blossom) supported by additional small icon (blossom - bool)

_Originally posted by @JesJehle in https://github.com/hydrocode-de/integra-frontend/issues/120#issuecomment-2098228833_

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #132 

Not finished yet. Implements only the first plot with default colors. I am expecting the color scheme to be delivered at some point, so no effort put into coloring things.
The second plot will be added, as well as a dropdown to select the variable (Nektar, pollen, blüten) to finish this PR.

### CODE REVIEW

**Comment by mmaelicke** [comment]
After a long evening this now also closes #188 which turned out to be concerningly complicated.

**Comment by mmaelicke** [comment]
@noobla11 this now implements the suggested purple circles around the tree. I am not sure if this is going into the right direction. Making the circles any larger may cause troubles for tree-lines with a lot of trees. However, if zoomed out a bit, the circles cannot be seen anymore.
Visualizing non-geo data geographically is not ideal and I am not sure if changing the radius makes it any better. 
But I am sure, that switching the circle with a symbol will definitely make it worse.

So: We can
1.  take the circle as it is
2. change it slightly (radius, color etc)
3. remove it again

in order to merge this PR somewhere soon

**Comment by noobla11** [comment]
We actually think this is pretty good. It would be nice if the colour is according to the colour scheme. I was thinking either the darkest pink (#DF77C1) for all OR the lighter pink for shrubs (#F0BCE1) and the slightly darker on for trees (#E797D1) if that is possible. But I don't know if this might be confusing. 

What definetly needs to change is the visual level of the circle. At the moment the circle is overlapping the tree icon. This is not the case for the biomass circle.

**Comment by mmaelicke** [comment]
Ok cool. I will finish this up asap. Just wnat to get first feedback before I put too much effort in this. Thanks

**Comment by mmaelicke** [comment]
Colors are now implemented. Turned out to be crazy complicated, as the data is internally implicitly ordered by the editing sorting (The first tree types show up first).

I reworked the full blossom, pollen and nectar calculation cycle and now the plots are ordered. 

Colors look quite decent on my old LCD screen, but seem to be way too bright on my new OLED 4K screen. You can barely see the difference between shrubs and trees, which is a pity because it was crazy complicated to implement that ^^

I will merge soon.

**Comment by noobla11** [comment]
@mmaelicke Does this mean changing the colours again will be complicated? Or do you only mean the implementation? Otherwise I will see if we can tweak the colours, on my screen the difference in colour is also too little. But for now I think this looks pretty good.

**Pull request merged**
