### PR TITLE
Rework tree selection

### LINKED ISSUE #204: Fix the Baumartenauswahl tab

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #204 

The new side card with Standortansprüche is **not** part of this PR, that will be handled in an extra issue.

This PR is not yet finished.

### CODE REVIEW

**Comment by mmaelicke** [comment]
@JoshuaBWWD this one is ready for review. 

It does not fit the drafts perfectly, but it is good enough to move forward. I think we need to cut some corners now, if we want a considerable part of the open issues closed until 15.7

**Comment by JoshuaBWWD** [comment]
Hi @mmaelicke 
Thanks for the implementation! 
I added two considerations in issue #204 (which are propably not super important, since they´re addressing layout style one tab title) and one as follows:
- in "Förderungsbedingungen": if you click on "Zusätzlich gelten Bestimmungen des Landes: Sachsen-Anhalt.
[Informieren Sie sich hier.]", you will be forwarded directly without an additional browser window opening. Maybe you can set it so that a new window opens, otherwise the planning will be completely discarded i.e. deleted.

And yes, I am aware that not everything can work out by 15.07. The main thing is that it works in general!
On Thursday at the latest I will create about 5 short video tutorials on how to use the tools (i.e. short desktop recordings). Do you think you can add them to the Welcoming page?

**Comment by mmaelicke** [comment]
@JoshuaBWWD I addressed both in this issue. However, I sticked to the left-alignment of Titles, as they are left-aligned everywhere. I you really prefer to break the design in only one component, I can do so, but we should open a new issue for that. (As it might involve some back and forth)

**Comment by JoshuaBWWD** [comment]
> @JoshuaBWWD I addressed both in this issue. However, I sticked to the left-alignment of Titles, as they are left-aligned everywhere. I you really prefer to break the design in only one component, I can do so, but we should open a new issue for that. (As it might involve some back and forth)

@mmaelicke awesome!! Thanks for the fast implementation... about "breaking the design in only one component", I think there was a misunderstanding, since I wrote "layout style one tab title" instead of "layout style and tab title"... sorry for that! If you meant something different, we can maybe discuss it tomorrow in the meeting.

**Pull request merged**
