### PR TITLE
Add abort functionality to NewTreeLineControl

### LINKED ISSUE #75: Edit mode navigation
This is an issue that was originally raised in #72 and should be solved somewhere in the near future

> 
> * Solution 1: we could disable or hide navigating back while editing, this would prevent the bug in the first place but force the user to continue editing and thus change the tree line event if he does not wont to. So this would be preferable if solution 2 is not feasible.

We cannot hide or disable the Browser back button. 

> * Solution 2: navigating back reverts the polygon back to the pre editing state. I imagine this could create some problematic state related issues. What do you think?

The only option I see is that we intercept the global navigate back event. The 'new' and 'edit' actions do not happen on their own page, so we need to do that on every page, where editing or creating might be activated. 
Once we have that, we can implement custom behavior and prevent or propagate the default event. 
For this, we maybe need to distinguish between the 'new' and the 'edit' action, which we do not do right now.
Additionally, I am not sure if a browser can force navigation events (like with alerts), as otherwise you could built a website, that does not allow navigating away from it...

_Originally posted by @mmaelicke in https://github.com/hydrocode-de/integra-frontend/issues/72#issuecomment-1838127219_

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #75

@JesJehle, this PR now adds a window listener to save features that are in MapboxDraw, before a edit abort or navigation occurs. I could confirm that creating a line, changing its properties, then click edit and navigate away now correctly preserves the state **before** editing and does not remove the feature anymore.

This is close to impossible with react-router, but quite straightforward with classic window events ^^

### CODE REVIEW

**Comment by JesJehle** [comment]
Hier mal wieder was neues:
https://www.loom.com/share/e3fc2bb403a4484fa8164789989565b3?sid=82055ad5-a1d0-49d5-a2ca-a988046b236e
um etwas komplexere Sachen zu beschreiben, könnte das eine große Hilfe sein.

**Comment by mmaelicke** [comment]
@JesJehle do you want a, possibly temporary, dirty hack to preserve the state of a feature, before it enters edit state, so that an 'abort' action reverts the state of the tree-lines as they were before editing, or do we sell the there-is-no-way-back behavior as a feature?
I think the 'correct' aborting behavior would be nicer, though give it a shot and only come back to you if it turns out to be more complicated than expected. Do you agree?

**Comment by JesJehle** [comment]
> @JesJehle do you want a, possibly temporary, dirty hack to preserve the state of a feature, before it enters edit state, so that an 'abort' action reverts the state of the tree-lines as they were before editing, or do we sell the there-is-no-way-back behavior as a feature? I think the 'correct' aborting behavior would be nicer, though give it a shot and only come back to you if it turns out to be more complicated than expected. Do you agree?

I think this is fine for now. So dont spend time on this one.

**Comment by mmaelicke** [comment]
works now as intended

**Comment by mmaelicke** [comment]
To make this one useful, we need to completely separate EDIT and CREATE dialogs in state. They can go together in the UI, but right now, the default behavior of CREATE interferes with EDIT, making a tree-line to show up differently after a successful and aborted edit action. 
The state of the `plantInPast` flag needs to be pre-populated differently, depending on the EDIT or CREATE mode, to then hide the checkbox during EDIT only.
This should be an easy fix, I will take care of that one later.

**Pull request closed without merging**
