### PR TITLE
Abundant species

### LINKED ISSUE #162: Add number of species
> Uploaded the data for the last part in the insect tab in /Insektendaten/Abundance_wide.xlsx

_Originally posted by @noobla11 in https://github.com/hydrocode-de/integra-frontend/issues/158#issuecomment-2150082956_

---
I'll make this an extra issue to finally merge #158

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #162 

The visuals are not implemented yet, still need to check if the calculations are correct. It is not super easy to do  the needed matrix manipulations in javascript.
The insect bit-array is mapped to the species, and filtered by the currently planted tree species. This composes a matrix of insect abundance, given the used tree species. Then the column sums of a bitwise OR combination is the number of abundant insect species.

Can be merged, if correct, and the visuals are implemented.

Are there preferences, where to put this number?

### CODE REVIEW

**Comment by noobla11** [comment]
We would like the title to be "Anzahl potentiell unterstützter Insektenarten" below the other two graphs. 

Information pop-up text: 

_Dieser Wert bezeichnet die Anzahl an potentiell unterstützten Insektenarten, welche sich aus der in Ihrem System vorhandenen Baum- und Strauchartenzusammensetzung ergibt._ 

Nice would be an insect icon on the left and the number on the right, both centered in the tab. We will provide a picture soon.

**Comment by mmaelicke** [comment]
@noobla11 @karpaddel, I already made the plots even smaller, to fit a thrid component into the tab and added the layout as requested. I also added an icon, that is already part of the icon-set used in the application. 
Maybe you can use the current state of this branch as a basis for change requests.

**Comment by karpaddel** [comment]
Now the two graphs look very flat and wide, could they not be made a little slimmer?

Otherwise we like it:) as already discussed, colors might be changed again:)

**Comment by mmaelicke** [comment]
This is fine for now. If there are future changes needed in the width of the graphs, or the Card itself, we can open a new issue for that. I'll merge, to continue

**Pull request merged**
